apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: lv-bridge
spec:
  replicas: 1
  bootstrapServers: lv-cluster-kafka-bootstrap.strimzi.svc.cluster.local:9092
  http:
    port: 8080
  enableMetrics: true
  template:
    bridgeContainer:
      env:
        - name: STRIMZI_TRACING_SYSTEM
          value: "opentelemetry"
        - name: OTEL_SERVICE_NAME
          value: lv-bridge-otel-service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-opentelemetry-collector.opensearch.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
          
  tracing:
    type: opentelemetry